export declare const PERMISSIONS: {
    readonly USERS_VIEW: "users:view";
    readonly USERS_CREATE: "users:create";
    readonly USERS_UPDATE: "users:update";
    readonly USERS_DELETE: "users:delete";
    readonly USERS_MANAGE_ROLES: "users:manage_roles";
    readonly ROLES_VIEW: "roles:view";
    readonly ROLES_CREATE: "roles:create";
    readonly ROLES_UPDATE: "roles:update";
    readonly ROLES_DELETE: "roles:delete";
    readonly CLIENTS_VIEW: "clients:view";
    readonly CLIENTS_CREATE: "clients:create";
    readonly CLIENTS_UPDATE: "clients:update";
    readonly CLIENTS_DELETE: "clients:delete";
    readonly TENDERS_VIEW: "tenders:view";
    readonly TENDERS_CREATE: "tenders:create";
    readonly TENDERS_UPDATE: "tenders:update";
    readonly TENDERS_DELETE: "tenders:delete";
    readonly PROJECTS_VIEW: "projects:view";
    readonly PROJECTS_CREATE: "projects:create";
    readonly PROJECTS_UPDATE: "projects:update";
    readonly PROJECTS_DELETE: "projects:delete";
    readonly COST_VIEW: "cost:view";
    readonly COST_CREATE: "cost:create";
    readonly COST_UPDATE: "cost:update";
    readonly COST_APPROVE: "cost:approve";
    readonly PROCUREMENT_VIEW: "procurement:view";
    readonly PROCUREMENT_CREATE: "procurement:create";
    readonly PROCUREMENT_UPDATE: "procurement:update";
    readonly PROCUREMENT_APPROVE: "procurement:approve";
    readonly SETTINGS_VIEW: "settings:view";
    readonly SETTINGS_UPDATE: "settings:update";
    readonly REPORTS_VIEW: "reports:view";
    readonly REPORTS_EXPORT: "reports:export";
    readonly AUDIT_VIEW: "audit:view";
    readonly IMPORTS_VIEW: "imports:view";
    readonly IMPORTS_RUN: "imports:run";
};
export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export declare const SYSTEM_ROLES: {
    readonly SUPER_ADMIN: "SUPER_ADMIN";
    readonly ADMIN: "ADMIN";
    readonly PROJECT_MANAGER: "PROJECT_MANAGER";
    readonly COST_CONTROLLER: "COST_CONTROLLER";
    readonly PROCUREMENT_OFFICER: "PROCUREMENT_OFFICER";
    readonly VIEWER: "VIEWER";
};
export declare const CURRENCIES: readonly ["SAR", "USD", "EUR", "GBP", "AED", "KWD", "QAR", "BHD"];
export type Currency = (typeof CURRENCIES)[number];
export declare const DEFAULT_PAGE = 1;
export declare const DEFAULT_LIMIT = 25;
export declare const MAX_LIMIT = 200;
export declare const AUDIT_MODULES: {
    readonly AUTH: "auth";
    readonly USERS: "users";
    readonly ROLES: "roles";
    readonly CLIENTS: "clients";
    readonly TENDERS: "tenders";
    readonly PROJECTS: "projects";
    readonly COST: "cost";
    readonly PROCUREMENT: "procurement";
    readonly SETTINGS: "settings";
    readonly IMPORTS: "imports";
};
//# sourceMappingURL=index.d.ts.map