ALTER TYPE "TenderStatus" ADD VALUE IF NOT EXISTS 'PRICING_IN_PROGRESS';
ALTER TYPE "TenderStatus" ADD VALUE IF NOT EXISTS 'PRICED_SUBMITTED';
ALTER TYPE "TenderStatus" ADD VALUE IF NOT EXISTS 'CONTRACTED';
